### ISSUE TITLE
how to merge it with ClusterCreator-main

### ISSUE THREAD

**Issue by web-differently12** [christensenjairus/Flux-Kubernetes#1]
hello Christen, 
And thanks you for your works, i have question: if i can merge two project and if you can tuto or video how to build this project with the first ClusterCreator-main
i try in my mac but u have this error 
You are currently using the kubectl context: docker-desktop
Do you want to continue with this context? (y/n) y
Continuing with context docker-desktop...

"1password" already exists with the same configuration, skipping
Error: Kubernetes cluster unreachable: Get "https://127.0.0.1:6443/version": dial tcp 127.0.0.1:6443: connect: connection refused

**Comment by christensenjairus** [comment]
This is more of an example repo. It's my production repo, but I haven't set it up in a way that others can use it. At least, not easily.

If I were you, I'd clone Flux's template repo [here](https://github.com/fluxcd/flux2-kustomize-helm-example) and use my repo as an example for what you *can* do. Incrementally add things to your own repo and edit as needed. 

Note: when I add helm charts, I just grab the entire helm values file (pasting in `release.yaml` files) and I edit from there. Because of that, I wouldn't recommending running my helm chart values without running a `git diff` against the default helm values so that you can see what I've edited. But my recommendation is to ***ignore my helm chart values and make your own instead***! :)
